// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.Models;

namespace NationalParks.Migrations
{
    [DbContext(typeof(NationalParksContext))]
    [Migration("20191101155626_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Established");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.Property<string>("Size");

                    b.Property<string>("States");

                    b.Property<string>("Visitors");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "The Grand Canyon, carved by the mighty Colorado River, is 277 miles (446 km) long, up to 1 mile (1.6 km) deep, and up to 15 miles (24 km) wide. Millions of years of erosion have exposed the multicolored layers of the Colorado Plateau in mesas and canyon walls, visible from both the north and south rims.",
                            Established = "February 26, 1919 ",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg/200px-USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg",
                            Name = "Grand Canyon",
                            Size = "1,201,647.03 acres",
                            States = "Arizona",
                            Visitors = "6,380,495 "
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "",
                            Established = "",
                            ImageURL = "",
                            Name = "",
                            Size = "",
                            States = "",
                            Visitors = ""
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "",
                            Established = "",
                            ImageURL = "",
                            Name = "",
                            Size = "",
                            States = "",
                            Visitors = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
